disqus:
  disable: false
googleAnalytics:
  anonymizeIP: true
  disable: false
  respectDoNotTrack: true
  useSessionStorage: false
instagram:
  disable: false
  simple: true
  disableInlineCSS: true
twitter:
  disable: false
  enableDNT: true
  simple: true
  disableInlineCSS: true
vimeo:
  disable: false
  enableDNT: true
  simple: true
youtube:
  disable: false
  privacyEnhanced: true
